#ifndef DEBUG_FLAG_H_
#define DEBUG_FLAG_H_

//#define FILL_REQUESTER_DEBUG
//#define TIMED_REQUESTER_DEBUG
//#define RR_ARBITER_DEBUG
//#define PRIORITY_ARBITER_DEBUG
//#define MAPPING_DEBUG
#define COMMAND_ISSUE_DEBUG
#define MEM_DEVICE_DEBUG

#endif
